name: Compilar OrcaSlicer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Baixar Dependências Pré-compiladas (OrcaSlicer Deps)
        run: |
          curl -L -o deps.zip https://github.com/SoftFever/OrcaSlicer-deps/releases/download/v1.0.0/OrcaSlicer-deps-win64.zip
          7z x deps.zip -o"D:/a/OrcaSlicer/OrcaSlicer/deps/build/OrcaSlicer_dep"

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Compilar Apenas o OrcaSlicer
        run: |
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="D:/a/OrcaSlicer/OrcaSlicer/deps/build/OrcaSlicer_dep/usr/local" ..
          cmake --build . --config Release --parallel

      - name: Compactar Executável
        run: |
          7z a -tzip OrcaSlicer_Custom_Win64.zip ./build/bin/Release/*

      - name: Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: OrcaSlicer-Windows-Build
          path: OrcaSlicer_Custom_Win64.zip
